### ISSUE TITLE
变量替换 - 表达式新接口改造

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-plugins-artifacts#10]
**描述您的需求**  

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by jordanzhangsz** [comment]
跟超哥讨论了一下，具体方案为：

**物料管理插件：**
1. 把物料包上传至S3，并解析相关的配置文件信息记录到wecmdb的CI - package
2. 解析包里的变量及配置变量取值的表达式，记录至wecmdb新增的CI - diff_conf_variable

**WeCMDB：**
1. "业务应用实例"增加一个属性“差异变量值”，配好自动填充规则，提取到上面配置的表达式。
2. 用户录入业务运行实例的时候，如自动填充规则取到的是表达式则再进行二次解析，提取到的值和变量名一起拼接成最终的字符串，填充至“差异变量值”。

**Saltstack插件：**
1. Saltstack变量替换的接口，直接使用数据模型表达式定位至"业务应用实例"的“差异变量值”取值，进行变量替换即可。
