### ISSUE TITLE
应用系统设计改名后，物料包出现多条记录

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-plugins-artifacts#137]
**描述您遇到的bug**  
应用系统设计改名后，物料包出现多个应用系统设计记录

**如何重现** 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/52971115/90750625-ab833380-e307-11ea-99c6-14977683b5eb.png)

**附加**

**Comment by royl88** [comment]
已解决
