### ISSUE TITLE
物料包名字中带有括号()导致物料包上传失败

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-plugins-artifacts#138]
**描述您遇到的bug**  
上传时物料包名字中带有括号，导致上传物料包失败。

如下特殊字符也不应该出现在物料包名字中，物料包插件做名字验证
**~!$&();|<>**

**如何重现** 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/52971115/90772526-463f3a80-e327-11ea-9ae5-0f7c280a96c1.png)

**附加**

**Comment by royl88** [comment]
v1.0.0版本查验，问题已修复。
