### ISSUE TITLE
物料包仓库分目录存储和定期清理

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-plugins-artifacts#141]
**描述您的需求**  
物料包使用的S3存储中，子系统的物料包全部放于相同路径下，不易于管理。
建议提供分系统或子系统存储物料包，便于查看、清理；
或者限制每个子系统上传物料包的个数，删除旧的记录，提供定时任务自动清理功能，没有单元、应用实例、数据库实例关联的物料包，定期删除。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

![image](https://user-images.githubusercontent.com/52971115/90950640-1bb7c380-e486-11ea-8792-2821257f4ee3.png)

**Comment by royl88** [comment]
v1.0.0已支持外置nexus物料管理，不再使用S3进行物料包管理，可以在nexus进行包的管理和清理工作，物料包插件内部仅做缓存目录清理。
