### ISSUE TITLE
物料包管理页面点击物料包数据报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-artifacts#32]
**描述您的需求**  
物料包管理页面点击物料包数据报错。
![image](https://user-images.githubusercontent.com/17095701/70767164-21a7c180-1d9b-11ea-908b-48dea46a5c3d.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by zhangsenfeng** [comment]
可能是所依赖的插件saltstack未启用导致的，目前无法重现。
请在解析物料包时保证saltstack已启用
