### ISSUE TITLE
建议物料包管理差异化变量的CMDB属性支持修改

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-artifacts#33]
**描述您的需求**  

建议物料包管理变量的CMDB属性支持修改。当前系统配置差异化变量保存后不能在物料包管理页面修改，很不方便。枚举管理页面管理的枚举code是表达式不便修改。

![image](https://user-images.githubusercontent.com/17095701/65411219-e1314b00-de1e-11e9-8ad0-5ea437017684.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
#88
