### ISSUE TITLE
差异化变量，配置解密时，添加过滤条件报错，无过滤条件OK。

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-plugins-artifacts#68]
**描述您遇到的bug**  
差异化变量，配置解密时，添加过滤条件报错，无过滤条件OK。

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
该问题是由于超过了CMDB差异化变量的数据库长度限制，需要增加限制，已在CMDB修复
