### ISSUE TITLE
插件依赖解耦优化

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/wecube-plugins-artifacts#86]
**描述您的需求**  
目前物料包依赖saltstack和wecmdb运行, 其访问地址通过两个单独属性配置
其配置较为复杂, 根据wecube的要求, 插件之间的访问必须通过gateway进行.

**预期行为**  
物料包插件不直接访问依赖插件的地址,而是通过wecube gateway进行统一访问

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
fixed
